# Generated by Django 6.1 on 2026-08-19 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Target Amount')),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Raised Amount')),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('NGN', 'NGN - Nigerian Naira'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('GHS', 'GHS - Ghanaian Cedi'), ('UGX', 'UGX - Ugandan Shilling'), ('TZS', 'TZS - Tanzanian Shilling')], default='USD', max_length=3, verbose_name='Currency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.media', verbose_name='Featured Image')),
            ],
            options={
                'verbose_name': 'Donation Goal',
                'verbose_name_plural': 'Donation Goals',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='Branch')),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('NGN', 'NGN - Nigerian Naira'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('GHS', 'GHS - Ghanaian Cedi'), ('UGX', 'UGX - Ugandan Shilling'), ('TZS', 'TZS - Tanzanian Shilling')], default='USD', max_length=3, verbose_name='Currency')),
                ('payment_methods', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], default='bank_transfer', max_length=200, verbose_name='Payment Methods')),
                ('mobile_money_number', models.CharField(blank=True, max_length=50, verbose_name='Mobile Money Number')),
                ('paypal_email', models.EmailField(blank=True, max_length=254, verbose_name='PayPal Email')),
                ('stripe_public_key', models.CharField(blank=True, max_length=200, verbose_name='Stripe Public Key')),
                ('donation_message', models.TextField(blank=True, help_text='Message displayed to donors', verbose_name='Donation Message')),
                ('funds_usage', models.TextField(blank=True, help_text='How donations will be used', verbose_name='Funds Usage')),
                ('impact_stories', models.TextField(blank=True, help_text='Stories of how donations have helped', verbose_name='Impact Stories')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('cta_text', models.CharField(default='Donate Now', max_length=100, verbose_name='CTA Text')),
                ('cta_url', models.URLField(blank=True, verbose_name='CTA URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.media', verbose_name='Featured Image')),
            ],
            options={
                'verbose_name': 'Donation Settings',
                'verbose_name_plural': 'Donation Settings',
            },
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200, verbose_name='Donor Name')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Donor Email')),
                ('donor_phone', models.CharField(blank=True, max_length=50, verbose_name='Donor Phone')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonymous')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('NGN', 'NGN - Nigerian Naira'), ('KES', 'KES - Kenyan Shilling'), ('ZAR', 'ZAR - South African Rand'), ('GHS', 'GHS - Ghanaian Cedi'), ('UGX', 'UGX - Ugandan Shilling'), ('TZS', 'TZS - Tanzanian Shilling')], default='USD', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Transaction ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('payment_response', models.JSONField(blank=True, null=True, verbose_name='Payment Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Donation Transaction',
                'verbose_name_plural': 'Donation Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='donations_d_status_b4dfd8_idx'), models.Index(fields=['transaction_id'], name='donations_d_transac_854447_idx'), models.Index(fields=['created_at'], name='donations_d_created_69fed6_idx'), models.Index(fields=['donor_email'], name='donations_d_donor_e_b96a33_idx')],
            },
        ),
    ]
