# Generated by Django 6.1 on 2026-08-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsettings',
            name='cta_text',
            field=models.CharField(blank=True, default='Donate Now', max_length=100, verbose_name='CTA Text'),
        ),
        migrations.AlterField(
            model_name='donationsettings',
            name='payment_methods',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash')], default='bank_transfer', max_length=200, verbose_name='Payment Methods'),
        ),
    ]
