# Generated by Django 6.1 on 2026-08-23 07:37

import apps.media_library.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'doc', 'docx', 'mp4', 'mp3']), apps.media_library.validators.validate_file_size, apps.media_library.validators.validate_file_type, apps.media_library.validators.validate_file_content, apps.media_library.validators.validate_image_dimensions], verbose_name='File'),
        ),
    ]
